// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesWebMvc.Data;

namespace SalesWebMvc.Migrations
{
    [DbContext(typeof(SalesWebMvcContext))]
    partial class SalesWebMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SalesWebMvc.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataNasci");

                    b.Property<string>("Nome");

                    b.Property<int>("NumeCel");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Comentario");

                    b.Property<DateTime>("Data");

                    b.Property<int?>("EspecialistaId");

                    b.Property<int>("StatusPagamento");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EspecialistaId");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Especialista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeDoutor");

                    b.Property<double>("Salario");

                    b.Property<int>("especialidade");

                    b.HasKey("Id");

                    b.ToTable("Especialista");
                });

            modelBuilder.Entity("SalesWebMvc.Models.Consulta", b =>
                {
                    b.HasOne("SalesWebMvc.Models.Cliente", "Cliente")
                        .WithMany("Consultas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("SalesWebMvc.Models.Especialista", "Especialista")
                        .WithMany()
                        .HasForeignKey("EspecialistaId");
                });
#pragma warning restore 612, 618
        }
    }
}
